export const projects = [
  {
    id: 1,
    title: 'Кирпичный дом в д. Покровская Слобода',
    description: 'Новая проводка в новом загородном доме.',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/sloboda/01.jpg'),
        preview: require('../images/projects/sloboda/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/sloboda/02.jpg'),
        preview: require('../images/projects/sloboda/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/sloboda/03.jpg'),
        preview: require('../images/projects/sloboda/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/sloboda/04.jpg'),
        preview: require('../images/projects/sloboda/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/sloboda/05.jpg'),
        preview: require('../images/projects/sloboda/preview/05.jpg'),
      },
      {
        id: 6,
        caption: 'Описание 6',
        link: require('../images/projects/sloboda/06.jpg'),
        preview: require('../images/projects/sloboda/preview/06.jpg'),
      },
      {
        id: 7,
        caption: 'Описание 7',
        link: require('../images/projects/sloboda/07.jpg'),
        preview: require('../images/projects/sloboda/preview/07.jpg'),
      },
      {
        id: 8,
        caption: 'Описание 8',
        link: require('../images/projects/sloboda/08.jpg'),
        preview: require('../images/projects/sloboda/preview/08.jpg'),
      },
      {
        id: 9,
        caption: 'Описание 9',
        link: require('../images/projects/sloboda/09.jpg'),
        preview: require('../images/projects/sloboda/preview/09.jpg'),
      },
      {
        id: 10,
        caption: 'Описание 10',
        link: require('../images/projects/sloboda/10.jpg'),
        preview: require('../images/projects/sloboda/preview/10.jpg'),
      },
      {
        id: 11,
        caption: 'Описание 11',
        link: require('../images/projects/sloboda/11.jpg'),
        preview: require('../images/projects/sloboda/preview/11.jpg'),
      },
      {
        id: 12,
        caption: 'Описание 12',
        link: require('../images/projects/sloboda/12.jpg'),
        preview: require('../images/projects/sloboda/preview/12.jpg'),
      },
    ],
  },
  {
    id: 2,
    title: 'Сборка щита для загородного дома',
    description:
      'Щит на базе автоматики Acti9 от производителя Schneider Electric. Сам щит от фирмы Hager',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/distribution-box/01.jpg'),
        preview: require('../images/projects/distribution-box/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/distribution-box/02.jpg'),
        preview: require('../images/projects/distribution-box/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/distribution-box/03.jpg'),
        preview: require('../images/projects/distribution-box/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/distribution-box/04.jpg'),
        preview: require('../images/projects/distribution-box/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/distribution-box/05.jpg'),
        preview: require('../images/projects/distribution-box/preview/05.jpg'),
      },
      {
        id: 6,
        caption: 'Описание 6',
        link: require('../images/projects/distribution-box/06.jpg'),
        preview: require('../images/projects/distribution-box/preview/06.jpg'),
      },
      {
        id: 7,
        caption: 'Описание 7',
        link: require('../images/projects/distribution-box/07.jpg'),
        preview: require('../images/projects/distribution-box/preview/07.jpg'),
      },
      {
        id: 8,
        caption: 'Описание 8',
        link: require('../images/projects/distribution-box/08.jpg'),
        preview: require('../images/projects/distribution-box/preview/08.jpg'),
      },
      {
        id: 9,
        caption: 'Описание 9',
        link: require('../images/projects/distribution-box/09.jpg'),
        preview: require('../images/projects/distribution-box/preview/09.jpg'),
      },
      {
        id: 10,
        caption: 'Описание 10',
        link: require('../images/projects/distribution-box/10.jpg'),
        preview: require('../images/projects/distribution-box/preview/10.jpg'),
      },
      {
        id: 11,
        caption: 'Описание 11',
        link: require('../images/projects/distribution-box/11.jpg'),
        preview: require('../images/projects/distribution-box/preview/11.jpg'),
      },
    ],
  },
  {
    id: 3,
    title: 'Квартира 120 кв.м. на ул. Псковская, д. 20',
    description:
      'Замена электропроводки со сборкой щита в новостройке на ул. Псковская, д. 20',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/yagodnaya/01.jpg'),
        preview: require('../images/projects/yagodnaya/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/yagodnaya/02.jpg'),
        preview: require('../images/projects/yagodnaya/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/yagodnaya/03.jpg'),
        preview: require('../images/projects/yagodnaya/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/yagodnaya/04.jpg'),
        preview: require('../images/projects/yagodnaya/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/yagodnaya/05.jpg'),
        preview: require('../images/projects/yagodnaya/preview/05.jpg'),
      },
      {
        id: 6,
        caption: 'Описание 6',
        link: require('../images/projects/yagodnaya/06.jpg'),
        preview: require('../images/projects/yagodnaya/preview/06.jpg'),
      },
      {
        id: 7,
        caption: 'Описание 7',
        link: require('../images/projects/yagodnaya/07.jpg'),
        preview: require('../images/projects/yagodnaya/preview/07.jpg'),
      },
      {
        id: 8,
        caption: 'Описание 8',
        link: require('../images/projects/yagodnaya/08.jpg'),
        preview: require('../images/projects/yagodnaya/preview/08.jpg'),
      },
      {
        id: 9,
        caption: 'Описание 9',
        link: require('../images/projects/yagodnaya/09.jpg'),
        preview: require('../images/projects/yagodnaya/preview/09.jpg'),
      },
      {
        id: 10,
        caption: 'Описание 10',
        link: require('../images/projects/yagodnaya/10.jpg'),
        preview: require('../images/projects/yagodnaya/preview/10.jpg'),
      },
    ],
  },
  {
    id: 4,
    title: 'Квартира 120 кв.м. на ул. Псковская, д. 13',
    description:
      'Замена электропроводки со сборкой щита в новостройке на ул. Псковская, д. 13',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/pskovskaya/01.jpg'),
        preview: require('../images/projects/pskovskaya/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/pskovskaya/02.jpg'),
        preview: require('../images/projects/pskovskaya/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/pskovskaya/03.jpg'),
        preview: require('../images/projects/pskovskaya/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/pskovskaya/04.jpg'),
        preview: require('../images/projects/pskovskaya/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/pskovskaya/05.jpg'),
        preview: require('../images/projects/pskovskaya/preview/05.jpg'),
      },
    ],
  },
  // {
  //   id: 2,
  //   title: 'Сборка щита для загородного дома',
  //   description: 'Сборка щита для загородного дома',
  //   images: {
  //     1: require('../images/projects/distribution-box/01.jpg'),
  //     2: require('../images/projects/distribution-box/02.jpg'),
  //     3: require('../images/projects/distribution-box/03.jpg'),
  //     4: require('../images/projects/distribution-box/04.jpg'),
  //     5: require('../images/projects/distribution-box/05.jpg'),
  //     6: require('../images/projects/distribution-box/06.jpg'),
  //     7: require('../images/projects/distribution-box/07.jpg'),
  //     8: require('../images/projects/distribution-box/08.jpg'),
  //     9: require('../images/projects/distribution-box/09.jpg'),
  //     10: require('../images/projects/distribution-box/10.jpg'),
  //     11: require('../images/projects/distribution-box/11.jpg'),
  //   },
  // },
  // {
  //   id: 3,
  //   title: 'Сборка щита для загородного дома',
  //   description: 'Сборка щита для загородного дома',
  //   images: {
  //     1: require('../images/projects/distribution-box/01.jpg'),
  //     2: require('../images/projects/distribution-box/02.jpg'),
  //     3: require('../images/projects/distribution-box/03.jpg'),
  //     4: require('../images/projects/distribution-box/04.jpg'),
  //     5: require('../images/projects/distribution-box/05.jpg'),
  //     6: require('../images/projects/distribution-box/06.jpg'),
  //     7: require('../images/projects/distribution-box/07.jpg'),
  //     8: require('../images/projects/distribution-box/08.jpg'),
  //     9: require('../images/projects/distribution-box/09.jpg'),
  //     10: require('../images/projects/distribution-box/10.jpg'),
  //     11: require('../images/projects/distribution-box/11.jpg'),
  //   },
  // },
  // {
  //   id: 4,
  //   title: 'Сборка щита для загородного дома',
  //   description: 'Сборка щита для загородного дома',
  //   images: {
  //     1: require('../images/projects/distribution-box/01.jpg'),
  //     2: require('../images/projects/distribution-box/02.jpg'),
  //     3: require('../images/projects/distribution-box/03.jpg'),
  //     4: require('../images/projects/distribution-box/04.jpg'),
  //     5: require('../images/projects/distribution-box/05.jpg'),
  //     6: require('../images/projects/distribution-box/06.jpg'),
  //     7: require('../images/projects/distribution-box/07.jpg'),
  //     8: require('../images/projects/distribution-box/08.jpg'),
  //     9: require('../images/projects/distribution-box/09.jpg'),
  //     10: require('../images/projects/distribution-box/10.jpg'),
  //     11: require('../images/projects/distribution-box/11.jpg'),
  //   },
  // },
  // {
  //   id: 5,
  //   title: 'Сборка щита для загородного дома',
  //   description: 'Сборка щита для загородного дома',
  //   images: {
  //     1: require('../images/projects/distribution-box/01.jpg'),
  //     2: require('../images/projects/distribution-box/02.jpg'),
  //     3: require('../images/projects/distribution-box/03.jpg'),
  //     4: require('../images/projects/distribution-box/04.jpg'),
  //     5: require('../images/projects/distribution-box/05.jpg'),
  //     6: require('../images/projects/distribution-box/06.jpg'),
  //     7: require('../images/projects/distribution-box/07.jpg'),
  //     8: require('../images/projects/distribution-box/08.jpg'),
  //     9: require('../images/projects/distribution-box/09.jpg'),
  //     10: require('../images/projects/distribution-box/10.jpg'),
  //     11: require('../images/projects/distribution-box/11.jpg'),
  //   },
  // },
  // {
  //   id: 6,
  //   title: 'Сборка щита для загородного дома',
  //   description: 'Сборка щита для загородного дома',
  //   images: {
  //     1: require('../images/projects/distribution-box/01.jpg'),
  //     2: require('../images/projects/distribution-box/02.jpg'),
  //     3: require('../images/projects/distribution-box/03.jpg'),
  //     4: require('../images/projects/distribution-box/04.jpg'),
  //     5: require('../images/projects/distribution-box/05.jpg'),
  //     6: require('../images/projects/distribution-box/06.jpg'),
  //     7: require('../images/projects/distribution-box/07.jpg'),
  //     8: require('../images/projects/distribution-box/08.jpg'),
  //     9: require('../images/projects/distribution-box/09.jpg'),
  //     10: require('../images/projects/distribution-box/10.jpg'),
  //     11: require('../images/projects/distribution-box/11.jpg'),
  //   },
  // },
];
