export const projects = [
  {
    id: 1,
    title: 'Кирпичный дом в д. Покровская Слобода',
    description: 'Новая проводка в новом загородном доме.',
    images: [
      {
        id: 1,
        caption: `Трёхфазный электрический щит. Автоматика и оболочка фирмы Hager.
        - Реле напряжения PH-260t, установленные пофазно.
        - Реле-переключатель фаз ПЭФ-319.
        - Контактор для функции мастер-клавиши.
        - Возможность подключения генератора или ИБП.`,
        link: require('../images/projects/sloboda/01.jpg'),
        preview: require('../images/projects/sloboda/preview/01.jpg'),
      },
      {
        id: 2,
        caption: `Проводка выполнена по потолку в гофре ПВХ
        - Серая гофра для силовых цепей.
        - Синяя гофра для слаботочнной сети.`,
        link: require('../images/projects/sloboda/02.jpg'),
        preview: require('../images/projects/sloboda/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/sloboda/03.jpg'),
        preview: require('../images/projects/sloboda/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/sloboda/04.jpg'),
        preview: require('../images/projects/sloboda/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/sloboda/05.jpg'),
        preview: require('../images/projects/sloboda/preview/05.jpg'),
      },
      {
        id: 6,
        caption: 'Описание 6',
        link: require('../images/projects/sloboda/06.jpg'),
        preview: require('../images/projects/sloboda/preview/06.jpg'),
      },
      {
        id: 7,
        caption: 'Описание 7',
        link: require('../images/projects/sloboda/07.jpg'),
        preview: require('../images/projects/sloboda/preview/07.jpg'),
      },
      {
        id: 8,
        caption: 'Описание 8',
        link: require('../images/projects/sloboda/08.jpg'),
        preview: require('../images/projects/sloboda/preview/08.jpg'),
      },
      {
        id: 9,
        caption: 'Описание 9',
        link: require('../images/projects/sloboda/09.jpg'),
        preview: require('../images/projects/sloboda/preview/09.jpg'),
      },
      {
        id: 10,
        caption: 'Описание 10',
        link: require('../images/projects/sloboda/10.jpg'),
        preview: require('../images/projects/sloboda/preview/10.jpg'),
      },
      {
        id: 11,
        caption: 'Описание 11',
        link: require('../images/projects/sloboda/11.jpg'),
        preview: require('../images/projects/sloboda/preview/11.jpg'),
      },
      {
        id: 12,
        caption: 'Описание 12',
        link: require('../images/projects/sloboda/12.jpg'),
        preview: require('../images/projects/sloboda/preview/12.jpg'),
      },
    ],
  },
  {
    id: 2,
    title: 'Сборка щита для загородного дома',
    description:
      'Щит на базе автоматики Acti9 от производителя Schneider Electric. Сам щит от фирмы Hager',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/distribution-box/01.jpg'),
        preview: require('../images/projects/distribution-box/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/distribution-box/02.jpg'),
        preview: require('../images/projects/distribution-box/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/distribution-box/03.jpg'),
        preview: require('../images/projects/distribution-box/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/distribution-box/04.jpg'),
        preview: require('../images/projects/distribution-box/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/distribution-box/05.jpg'),
        preview: require('../images/projects/distribution-box/preview/05.jpg'),
      },
      {
        id: 6,
        caption: 'Описание 6',
        link: require('../images/projects/distribution-box/06.jpg'),
        preview: require('../images/projects/distribution-box/preview/06.jpg'),
      },
      {
        id: 7,
        caption: 'Описание 7',
        link: require('../images/projects/distribution-box/07.jpg'),
        preview: require('../images/projects/distribution-box/preview/07.jpg'),
      },
      {
        id: 8,
        caption: 'Описание 8',
        link: require('../images/projects/distribution-box/08.jpg'),
        preview: require('../images/projects/distribution-box/preview/08.jpg'),
      },
      {
        id: 9,
        caption: 'Описание 9',
        link: require('../images/projects/distribution-box/09.jpg'),
        preview: require('../images/projects/distribution-box/preview/09.jpg'),
      },
      {
        id: 10,
        caption: 'Описание 10',
        link: require('../images/projects/distribution-box/10.jpg'),
        preview: require('../images/projects/distribution-box/preview/10.jpg'),
      },
      {
        id: 11,
        caption: 'Описание 11',
        link: require('../images/projects/distribution-box/11.jpg'),
        preview: require('../images/projects/distribution-box/preview/11.jpg'),
      },
    ],
  },
  {
    id: 3,
    title: 'Квартира 120 кв.м. на ул. Псковская, д. 20',
    description:
      'Замена электропроводки со сборкой щита в новостройке на ул. Псковская, д. 20',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/yagodnaya/01.jpg'),
        preview: require('../images/projects/yagodnaya/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/yagodnaya/02.jpg'),
        preview: require('../images/projects/yagodnaya/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/yagodnaya/03.jpg'),
        preview: require('../images/projects/yagodnaya/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/yagodnaya/04.jpg'),
        preview: require('../images/projects/yagodnaya/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/yagodnaya/05.jpg'),
        preview: require('../images/projects/yagodnaya/preview/05.jpg'),
      },
      {
        id: 6,
        caption: 'Описание 6',
        link: require('../images/projects/yagodnaya/06.jpg'),
        preview: require('../images/projects/yagodnaya/preview/06.jpg'),
      },
      {
        id: 7,
        caption: 'Описание 7',
        link: require('../images/projects/yagodnaya/07.jpg'),
        preview: require('../images/projects/yagodnaya/preview/07.jpg'),
      },
      {
        id: 8,
        caption: 'Описание 8',
        link: require('../images/projects/yagodnaya/08.jpg'),
        preview: require('../images/projects/yagodnaya/preview/08.jpg'),
      },
      {
        id: 9,
        caption: 'Описание 9',
        link: require('../images/projects/yagodnaya/09.jpg'),
        preview: require('../images/projects/yagodnaya/preview/09.jpg'),
      },
      {
        id: 10,
        caption: 'Описание 10',
        link: require('../images/projects/yagodnaya/10.jpg'),
        preview: require('../images/projects/yagodnaya/preview/10.jpg'),
      },
    ],
  },
  {
    id: 4,
    title: 'Квартира 120 кв.м. на ул. Псковская, д. 13',
    description:
      'Замена электропроводки со сборкой щита в новостройке на ул. Псковская, д. 13',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/pskovskaya/01.jpg'),
        preview: require('../images/projects/pskovskaya/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/pskovskaya/02.jpg'),
        preview: require('../images/projects/pskovskaya/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/pskovskaya/03.jpg'),
        preview: require('../images/projects/pskovskaya/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/pskovskaya/04.jpg'),
        preview: require('../images/projects/pskovskaya/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/pskovskaya/05.jpg'),
        preview: require('../images/projects/pskovskaya/preview/05.jpg'),
      },
    ],
  },
  {
    id: 5,
    title: 'Квартира 100 кв.м. на ул. Фрязиновская, д. 25г',
    description:
      'Замена электропроводки со сборкой щита в новостройке на ул. Фрязиновская, д. 25г',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/fryazinovskaya/01.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/fryazinovskaya/02.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/fryazinovskaya/03.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/fryazinovskaya/04.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/fryazinovskaya/05.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/05.jpg'),
      },
      {
        id: 6,
        caption: 'Описание 6',
        link: require('../images/projects/fryazinovskaya/06.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/06.jpg'),
      },
      {
        id: 7,
        caption: 'Описание 7',
        link: require('../images/projects/fryazinovskaya/07.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/07.jpg'),
      },
      {
        id: 8,
        caption: 'Описание 8',
        link: require('../images/projects/fryazinovskaya/08.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/08.jpg'),
      },
      {
        id: 9,
        caption: 'Описание 9',
        link: require('../images/projects/fryazinovskaya/09.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/09.jpg'),
      },
      {
        id: 10,
        caption: 'Описание 10',
        link: require('../images/projects/fryazinovskaya/10.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/10.jpg'),
      },
      {
        id: 11,
        caption: 'Описание 11',
        link: require('../images/projects/fryazinovskaya/11.jpg'),
        preview: require('../images/projects/fryazinovskaya/preview/11.jpg'),
      },
    ],
  },
  {
    id: 6,
    title: 'Сборка трёхфазного щита для загородного дома в д. Тимонино',
    description: 'Трёхфазный щит на базе автоматики Resi9.',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/timonino/01.jpg'),
        preview: require('../images/projects/timonino/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/timonino/02.jpg'),
        preview: require('../images/projects/timonino/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/timonino/03.jpg'),
        preview: require('../images/projects/timonino/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/timonino/04.jpg'),
        preview: require('../images/projects/timonino/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/timonino/05.jpg'),
        preview: require('../images/projects/timonino/preview/05.jpg'),
      },
      {
        id: 6,
        caption: 'Описание 6',
        link: require('../images/projects/timonino/06.jpg'),
        preview: require('../images/projects/timonino/preview/06.jpg'),
      },
      {
        id: 7,
        caption: 'Описание 7',
        link: require('../images/projects/timonino/07.jpg'),
        preview: require('../images/projects/timonino/preview/07.jpg'),
      },
    ],
  },
  {
    id: 7,
    title: 'Электропроводка в стиле "ретро"',
    description: 'Ретро с разных объектов',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/retro/01.jpg'),
        preview: require('../images/projects/retro/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/retro/02.jpg'),
        preview: require('../images/projects/retro/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/retro/03.jpg'),
        preview: require('../images/projects/retro/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/retro/04.jpg'),
        preview: require('../images/projects/retro/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/retro/05.jpg'),
        preview: require('../images/projects/retro/preview/05.jpg'),
      },
      {
        id: 6,
        caption: 'Описание 6',
        link: require('../images/projects/retro/06.jpg'),
        preview: require('../images/projects/retro/preview/06.jpg'),
      },
      {
        id: 7,
        caption: 'Описание 7',
        link: require('../images/projects/retro/07.jpg'),
        preview: require('../images/projects/retro/preview/07.jpg'),
      },
      {
        id: 8,
        caption: 'Описание 8',
        link: require('../images/projects/retro/08.jpg'),
        preview: require('../images/projects/retro/preview/08.jpg'),
      },
      {
        id: 9,
        caption: 'Описание 9',
        link: require('../images/projects/retro/09.jpg'),
        preview: require('../images/projects/retro/preview/09.jpg'),
      },
      {
        id: 10,
        caption: 'Описание 10',
        link: require('../images/projects/retro/10.jpg'),
        preview: require('../images/projects/retro/preview/10.jpg'),
      },
    ],
  },
  {
    id: 8,
    title: 'Сборка трёхфазного щита с программируемым реле',
    description:
      'Сборка трёхфазного щита с программируемым реле ProRelay от EKF',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/yurovo/01.jpg'),
        preview: require('../images/projects/yurovo/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/yurovo/02.jpg'),
        preview: require('../images/projects/yurovo/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/yurovo/03.jpg'),
        preview: require('../images/projects/yurovo/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/yurovo/04.jpg'),
        preview: require('../images/projects/yurovo/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/yurovo/05.jpg'),
        preview: require('../images/projects/yurovo/preview/05.jpg'),
      },
    ],
  },
  {
    id: 9,
    title: 'Разные фото рабочего процесса',
    description: 'Фотографии рабочего процесса и не только',
    images: [
      {
        id: 1,
        caption: 'Описание 1',
        link: require('../images/projects/wip/01.jpg'),
        preview: require('../images/projects/wip/preview/01.jpg'),
      },
      {
        id: 2,
        caption: 'Описание 2',
        link: require('../images/projects/wip/02.jpg'),
        preview: require('../images/projects/wip/preview/02.jpg'),
      },
      {
        id: 3,
        caption: 'Описание 3',
        link: require('../images/projects/wip/03.jpg'),
        preview: require('../images/projects/wip/preview/03.jpg'),
      },
      {
        id: 4,
        caption: 'Описание 4',
        link: require('../images/projects/wip/04.jpg'),
        preview: require('../images/projects/wip/preview/04.jpg'),
      },
      {
        id: 5,
        caption: 'Описание 5',
        link: require('../images/projects/wip/05.jpg'),
        preview: require('../images/projects/wip/preview/05.jpg'),
      },
      {
        id: 6,
        caption: 'Описание 6',
        link: require('../images/projects/wip/06.jpg'),
        preview: require('../images/projects/wip/preview/06.jpg'),
      },
      {
        id: 7,
        caption: 'Описание 7',
        link: require('../images/projects/wip/07.jpg'),
        preview: require('../images/projects/wip/preview/07.jpg'),
      },
      {
        id: 8,
        caption: 'Описание 8',
        link: require('../images/projects/wip/08.jpg'),
        preview: require('../images/projects/wip/preview/08.jpg'),
      },
      {
        id: 9,
        caption: 'Описание 9',
        link: require('../images/projects/wip/09.jpg'),
        preview: require('../images/projects/wip/preview/09.jpg'),
      },
      {
        id: 10,
        caption: 'Описание 10',
        link: require('../images/projects/wip/10.jpg'),
        preview: require('../images/projects/wip/preview/10.jpg'),
      },
      {
        id: 11,
        caption: 'Описание 11',
        link: require('../images/projects/wip/11.jpg'),
        preview: require('../images/projects/wip/preview/11.jpg'),
      },
      {
        id: 12,
        caption: 'Описание 12',
        link: require('../images/projects/wip/12.jpg'),
        preview: require('../images/projects/wip/preview/12.jpg'),
      },
      {
        id: 13,
        caption: 'Описание 13',
        link: require('../images/projects/wip/13.jpg'),
        preview: require('../images/projects/wip/preview/13.jpg'),
      },
      {
        id: 14,
        caption: 'Описание 14',
        link: require('../images/projects/wip/14.jpg'),
        preview: require('../images/projects/wip/preview/14.jpg'),
      },
    ],
  },
];
