export const projects = [
  {
    id: 1,
    title: 'Кирпичный дом в д. Покровская Слобода',
    description: 'Новая проводка в новом загородном доме.',
    images: {
      1: require('../images/projects/sloboda/01.jpg'),
      2: require('../images/projects/sloboda/02.jpg'),
      3: require('../images/projects/sloboda/03.jpg'),
      4: require('../images/projects/sloboda/04.jpg'),
      5: require('../images/projects/sloboda/05.jpg'),
      6: require('../images/projects/sloboda/06.jpg'),
      7: require('../images/projects/sloboda/07.jpg'),
      8: require('../images/projects/sloboda/08.jpg'),
      9: require('../images/projects/sloboda/09.jpg'),
      10: require('../images/projects/sloboda/10.jpg'),
      11: require('../images/projects/sloboda/11.jpg'),
      12: require('../images/projects/sloboda/12.jpg'),
    },
  },
  {
    id: 2,
    title: 'Сборка щита для загородного дома',
    description: 'Сборка щита для загородного дома',
    images: {
      1: require('../images/projects/distribution-box/01.jpg'),
      2: require('../images/projects/distribution-box/02.jpg'),
      3: require('../images/projects/distribution-box/03.jpg'),
      4: require('../images/projects/distribution-box/04.jpg'),
      5: require('../images/projects/distribution-box/05.jpg'),
      6: require('../images/projects/distribution-box/06.jpg'),
      7: require('../images/projects/distribution-box/07.jpg'),
      8: require('../images/projects/distribution-box/08.jpg'),
      9: require('../images/projects/distribution-box/09.jpg'),
      10: require('../images/projects/distribution-box/10.jpg'),
      11: require('../images/projects/distribution-box/11.jpg'),
    },
  },
  {
    id: 3,
    title: 'Сборка щита для загородного дома',
    description: 'Сборка щита для загородного дома',
    images: {
      1: require('../images/projects/distribution-box/01.jpg'),
      2: require('../images/projects/distribution-box/02.jpg'),
      3: require('../images/projects/distribution-box/03.jpg'),
      4: require('../images/projects/distribution-box/04.jpg'),
      5: require('../images/projects/distribution-box/05.jpg'),
      6: require('../images/projects/distribution-box/06.jpg'),
      7: require('../images/projects/distribution-box/07.jpg'),
      8: require('../images/projects/distribution-box/08.jpg'),
      9: require('../images/projects/distribution-box/09.jpg'),
      10: require('../images/projects/distribution-box/10.jpg'),
      11: require('../images/projects/distribution-box/11.jpg'),
    },
  },
  {
    id: 4,
    title: 'Сборка щита для загородного дома',
    description: 'Сборка щита для загородного дома',
    images: {
      1: require('../images/projects/distribution-box/01.jpg'),
      2: require('../images/projects/distribution-box/02.jpg'),
      3: require('../images/projects/distribution-box/03.jpg'),
      4: require('../images/projects/distribution-box/04.jpg'),
      5: require('../images/projects/distribution-box/05.jpg'),
      6: require('../images/projects/distribution-box/06.jpg'),
      7: require('../images/projects/distribution-box/07.jpg'),
      8: require('../images/projects/distribution-box/08.jpg'),
      9: require('../images/projects/distribution-box/09.jpg'),
      10: require('../images/projects/distribution-box/10.jpg'),
      11: require('../images/projects/distribution-box/11.jpg'),
    },
  },
  {
    id: 5,
    title: 'Сборка щита для загородного дома',
    description: 'Сборка щита для загородного дома',
    images: {
      1: require('../images/projects/distribution-box/01.jpg'),
      2: require('../images/projects/distribution-box/02.jpg'),
      3: require('../images/projects/distribution-box/03.jpg'),
      4: require('../images/projects/distribution-box/04.jpg'),
      5: require('../images/projects/distribution-box/05.jpg'),
      6: require('../images/projects/distribution-box/06.jpg'),
      7: require('../images/projects/distribution-box/07.jpg'),
      8: require('../images/projects/distribution-box/08.jpg'),
      9: require('../images/projects/distribution-box/09.jpg'),
      10: require('../images/projects/distribution-box/10.jpg'),
      11: require('../images/projects/distribution-box/11.jpg'),
    },
  },
  {
    id: 6,
    title: 'Сборка щита для загородного дома',
    description: 'Сборка щита для загородного дома',
    images: {
      1: require('../images/projects/distribution-box/01.jpg'),
      2: require('../images/projects/distribution-box/02.jpg'),
      3: require('../images/projects/distribution-box/03.jpg'),
      4: require('../images/projects/distribution-box/04.jpg'),
      5: require('../images/projects/distribution-box/05.jpg'),
      6: require('../images/projects/distribution-box/06.jpg'),
      7: require('../images/projects/distribution-box/07.jpg'),
      8: require('../images/projects/distribution-box/08.jpg'),
      9: require('../images/projects/distribution-box/09.jpg'),
      10: require('../images/projects/distribution-box/10.jpg'),
      11: require('../images/projects/distribution-box/11.jpg'),
    },
  },
];
